controller_list:
  - name: fake_pusher_controller
    type: $(arg fake_execution_type)
    joints:
      - pusher_joint
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
  - name: fake_handee_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_3
      - joint_4
initial:  # Define initial robot poses per group
  - group: pusher
    pose: down